[package]
name = "monitor-ipv6"
version = "1.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simple_logger = "1.16"
get_if_addrs = "0.5"
clap = { version = "3.0", features = ["derive", "env"] }

[profile.release]
opt-level = 'z' # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'
